[package]
name = "soratun-rs"
version = "0.1.0"
edition = "2021"
authors = ["kaoru <k@warpnine.io>"]
description = "Example of using Rust to call a function in the libsoratun"
license = "MIT"

[dependencies]
clap = { version = "4.3.17", features = ["derive"] }
